version: '3.7'

services:
  api:
    build:
      context: .
    container_name: api
    ports:
      - 8000:8000
    environment:
      APP_HOST: http://localhost:8000
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: wishlist
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    restart: always
  